kind: pipeline
name: api
steps:
  # api unit test
    - name: lint
    image: node:16
    group: testing
    commands:
      - npm run lint

  - name: testing
    image: node:16
    group: testing
    commands:
      - npm run test 
      
    when:
      branch: master
      event: push
