kind: pipeline
name: api
steps:
  # api unit test
  - name: run lint
    image: node:16
    depends_on: [clone]
    commands:
      - npm ci
      - npm run lint
    when:
      branch: master
      event: push

  - name: run test
    image: node:16
    depends_on: [clone]
    commands:
      - npm run test
    when:
      branch: master
      event: push

  - name: run build
    image: node:16
    depends_on: [clone]
    commands:
      - npm run build
    when:
      branch: master
      event: push
