kind: pipeline
name: api
steps:
  - name: install
    image: node:16
    commands:
      - node -v
      - npm -v
      - npm config set cache .npm-cache
      - npm install 
      
  - name: lint
    image: node:16
    group: testing
    commands:
      - npm run lint

  - name: testing
    image: node:16
    group: testing
    commands:
      - npm run test 
      
    when:
      branch: master
      event: push
