kind: pipeline
 name: drone-test
  steps:
   - name: restore-cache
     image: drillster/drone-volume-cache
     restore: true
     mount:
       - ./.npm-chahe
       - ./node_modules
     volumes:
       - /tmp/chahe/:cache

  - name: install
    image: node:16
    commands:
      - node -v
      - npm -v
      - npm config set cache .npm-cache
      - npm install 

  - name: lint
    image: node:16
    group: testing
    commands:
      - npm run lint

  - name: testing
    image: node:16
    group: testing
    commands:
      - npm run test   

  - name: build
    image: node:16
    group: testing
    commands:
      - npm run build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.npm-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: master

