kind: pipeline
name: api
steps:
  # api unit test
  - name: test
    image: node:16
    depends_on: [clone]
    commands:
      - npm install
      - npm run test
    when:
      branch: master
      event: push
