# # drone server 部署
# version: "2"
# services:
#   drone-server:
#     image: drone/drone:1.0.0
#     ports:
#       - 8081:80
#       - 443:443
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /var/lib/drone:/data
#     restart: always
#     environment:
#       - DRONE_GITHUB=true
#       - DRONE_GITHUB_SERVER=${DRONE_GITHUB_SERVER}
#       - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
#       - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
#       - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
#       - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
#       - DRONE_SECRET_SECRET=${DRONE_RPC_SECRETS}

version: '3'
services:
   test-drone:
     build:
      context: .
      dockerfile: Dockerfile
    image: test-drone
    container_name: test-drone
    ports:
       - 8081:3000
    test-redis:
      image: redis
      container_name: test-redis
      ports:
         - 6378:6379
      environment:
         - TZ=Asia/shanghai
